# docker-compose.yml - a sample docker-compose configuration that brings
# sli runner up and running.
#
# ps.: assumes that `concourse` has been brought up using the
# `docker-compose.yml` file from `concourse/concourse`
#
#     git clone https://github.com/concourse/concourse concourse
#     cd $_
#
#     docker-compose up -d --build
#

version: '3'

services:
  slirunner:
    image: cirocosta/slirunner
    container_name: 'slirunner'
    ports:
        - '9001:9001'
    command:
      - start
      - --target=test
      - --concourse-url=<CONCOURSE-URL>
      - --username=<CONCOURSE-USERNAME>
      - --password=<CONCOURSE-PASSWORD>